### ISSUE TITLE
ConcurrentHashMap does NOT work in Xamarin Binding project.

### ISSUE THREAD

**Issue by lin-zy1229** [abbyysdk/RTR-SDK.Android#11]
First of all, Xamarin Binding Generator seems to have errors.

Here is code block I use in Xamarin.

```
Java.Util.Concurrent.ConcurrentHashMap map = new Java.Util.Concurrent.ConcurrentHashMap();
var key = new byte[] { 1, 2, 3 };
var data = new byte[] { 1, 2, 3, 4, 5 };

map.Put(key, data);
var val = map.Get(key); // null, WHY?

IEnumeration keys = map.Keys();
while (keys.HasMoreElements)
{
    var k = keys.NextElement();
    var val2 = map.Get(k); // NOT null, val2 is byte array of {1,2,3,4,5}
}
```

I expected `val `is byte array (data), but `val `is null, while `val2 `is not null.

But this Java code works very well.

```
java.util.concurrent.ConcurrentHashMap map = new java.util.concurrent.ConcurrentHashMap();

byte[] key = {1, 2, 3};
byte[] data = {1, 2, 3, 4, 5};

map.put(key, data);
Object o = map.get(key); // byte array of {1,2,3,4,5}
```

As you see, same code for `ConcurrentHashMap` doesn't work in Xamarin Android, while it works in Android Native.

By the way, you used it in `com.abbyy.mobile.rtr.RecognitionService`, tried to get value using byte array as key.
Your code is following:
```
    private ConcurrentHashMap<byte[], BlockingQueue<byte[]>> queuesMap = new ConcurrentHashMap();
    public void submitRequestedFrame(byte[] data) {
        if(this.workers != null) {
            BlockingQueue<byte[]> queue = (BlockingQueue)this.queuesMap.get(data);
            if(queue != null) {
                queue.offer(data);
            } else {
                Log.w("RecognitionService", "You must fill in and pass to the 'submitRequestedFrame' the same buffer, which was provided in the 'onRequestLatestFrame' call");
            }
        }
    }
```

In Xamarin Binding for this part, `queue` is always `null`.
So you will need to avoid to use `ConcurrentHashMap<byte[], BlockingQueue<byte[]>>`.

Hope you update your sdk for Android as soon as possible, so that anyone can use it for Xamarin project also.

Of course, I am a user purchased the license.

**Comment by aleksey-ka** [comment]
Thank you for the feedback!

We don't have any official Xamarin support as of now, but we surely want to make our SDK available for all users. The problem that you describe seems to be a bug in Xamarin. We can try and find a way around it, but you'll have to go through the support so that the issue gets priority and resources allocated. A more proper way thought, from a developer's perspective, would be to solve it on Xamarin side.

In this channel you talk directly to the developers. We can answer questions, solve small problems. This issue seems to require some work and a lot of testing.

**Comment by lin-zy1229** [comment]
Thanks for your kind answer.

**Comment by lin-zy1229** [comment]
I completed it finally.
https://goo.gl/xgtmMM
Thanks a lot.

**Comment by aleksey-ka** [comment]
Thank you for the video!

**Comment by aradhwan** [comment]
Hello @aleksey-ka, @lin-zy1229 
I am running into the same issue. I need some help to get over it.
Any help would be very much appreciated.
Thanks.

**Comment by jderrac** [comment]
Hello, I managed to make it work. My code is really dirty ATM and I won't share it as it is.
The problem is with Xamarin/Mono marshaling of the Abbyy SDK provided `byte[]` buffer, when the Abbyy SDK gets the buffer filed by the camera it can't find it in his HashMap because Xamarin cloned/copied it around.
You need to pass an `IntPtr` instead of a `byte[]` between the `Camera.IPreviewCallback.OnPreviewFrame(...)` and `IRecognitionService.SubmitRequestedFrame(...)`.

To do so you have to add a few Additions in the Xamarin binding library project and also extend the Camera class.

A good starting point is to look at this project: https://github.com/jamesathey/FastAndroidCamera which does half the work for the Android Camera class.

I hope it'll help you @aradhwan
