### ISSUE TITLE
Is possible to get all scanned texts and show on my custom activity

### ISSUE THREAD

**Issue by matghazaryan** [abbyysdk/RTR-SDK.Android#2]
Is it possible to scan driver license and get all data to show my custom activity.

**Comment by aleksey-ka** [comment]
I'm afraid I don't understand what the issue is. If it is just a question, the answer is yes, you can extract some text from driver licenses or other ids. The result might be not very good though if you use the general text capture. More specialized **data capture** approach will usually give better results. We have ready to use data capture profiles for many types of ids (but in the extended version only)

**Comment by matghazaryan** [comment]
Could I test data capture before I buy extended version? I tried your example and I always has license error?

**Comment by aleksey-ka** [comment]
You should contact our sales department [here](http://rtrsdk.com/contacts/) to request a free trial. If you have any technical issues we will be glad to answer them. Also check out this [forum](http://forum.ocrsdk.com/cat/real-time-recognition-sdk/).

RE: license errors
In the free online version the only type of data capture currently available is **single field regular expressions**.

Thank you for your interest in our product!
Best regards
